name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install PureScript tooling
        run: npm install -g purescript@0.15.8 spago@next esbuild@0.13.12 purs-tidy@0.9.2

      - name: Check formatting
        run: purs-tidy check lib site

      - name: Cache PureScript dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.yaml') }}
          path: |
            .spago
            output

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install PureScript dependencies
        run: spago install

      - name: Build source
        run: spago build --pedantic-packages --purs-args '--censor-lib --strict'

      - name: Run tests
        run: spago test

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build site
        run: npm run bundle

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public