name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          purs-tidy: "latest"

      - name: Check formatting
        run: purs-tidy check src test

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install main PureScript dependencies
        run: spago install

      - name: Build main source
        run: spago build --no-install --purs-args '--censor-lib --strict'

      - name: Run tests
        run: spago -x test.dhall test

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build site
        run: npm run bundle

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
