name: site

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install PureScript dependencies
        run: spago -x site.dhall install

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build
        run: npm run bundle

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
